services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Talav\UserBundle\:
    resource: '../../*/*'
    exclude: '../../{DependencyInjection,Entity,Event,Form,Model,Migrations,Tests,vendor,Controller,EventSubscriber}'
  talav.media.provider.file:
    class: Talav\Component\Media\Provider\FileProvider
    arguments:
      $name: 'file'
    public: true
  talav.media.provider.image:
    class: Talav\Component\Media\Provider\ImageProvider
    arguments:
      $name: 'image'
    public: true
  talav.media.provider.pool:
    class: Talav\Component\Media\Provider\ProviderPool
    public: true
  talav.media.generator.default:
    class: Talav\Component\Media\Generator\DefaultGenerator
    public: true
  talav.media.cdn.server:
    class: Talav\Component\Media\Cdn\Server
    public: true
  Talav\Component\Media\Subscriber\MediaEventSubscriber:
    class: Talav\Component\Media\Subscriber\MediaEventSubscriber
    arguments: ['@talav.media.provider.pool']
    tags: ['doctrine.event_subscriber']
  talav.media.form.type.media:
    class: Talav\MediaBundle\Form\Type\MediaType
    arguments: ['@talav.media.provider.pool', '@app.manager.media']
    tags:
      - { name: form.type }