services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Talav\MediaBundle\:
    resource: '../../*/*'
    exclude: '../../{DependencyInjection,Entity,Event,Form,Model,Migrations,Tests,vendor,Controller,EventSubscriber}'
  talav.media.provider.file:
    class: Talav\Component\Media\Provider\FileProvider
    arguments:
      $name: 'file'
    public: true
  talav.media.provider.image:
    class: Talav\Component\Media\Provider\ImageProvider
    arguments:
      $name: 'image'
    public: true
  talav.media.provider.pool:
    class: Talav\Component\Media\Provider\ProviderPool
    public: true
  Talav\Component\Media\Provider\ProviderPool:
    alias: talav.media.provider.pool
  talav.media.generator.uuid:
    class: Talav\Component\Media\Generator\UuidGenerator
    public: true
  talav.media.league.glide:
    class: League\Glide\Server
    factory: ['League\Glide\ServerFactory', 'create']
    arguments:
      - { source: "%kernel.cache_dir%", cache: "%kernel.cache_dir%", cache_path_prefix: 'thumb'}
  talav.media.thumbnail.glide:
    class: Talav\Component\Media\Thumbnail\GlideServer
    arguments: ['@talav.media.league.glide', "%kernel.cache_dir%"]
    public: true
  Talav\Component\Media\Thumbnail\ThumbnailInterface:
    alias: talav.media.thumbnail.glide
  talav.media.cdn.server:
    class: Talav\Component\Media\Cdn\Server
    public: true
  talav.media.form.type.media:
    class: Talav\MediaBundle\Form\Type\MediaType
    arguments: ['@talav.media.provider.pool', '@app.manager.media']
    tags:
      - { name: form.type }
  Talav\Component\Media\Message\CommandHandler\:
    resource: '../../../vendor/talav/media/src/Message/CommandHandler/*/*'
  Talav\Component\Media\Mapper\Configurator\:
    resource: '../../../vendor/talav/media/src/Mapper/Configurator/*'