name: Split Monorepo

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  provide_packages_json:
    # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
    # see https://stackoverflow.com/a/62953566/1348344
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: output_data
        run: |
          content=`cat ./monorepo-builder.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=matrix::$content"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package.name }} (${{ matrix.package.path }})
        uses: symplify/github-action-monorepo-split@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.TALAV_WORKFLOW_SECRET }}
        with:
          package_directory: 'packages/${{ matrix.package.path }}'
          repository_organization: 'talav'
          repository_name: '${{ matrix.package.name }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "master"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package.name }} (${{ matrix.package.path }})
        uses: symplify/github-action-monorepo-split@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.TALAV_WORKFLOW_SECRET }}
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package_directory: 'packages/${{ matrix.package.path }}'
          repository_organization: 'talav'
          repository_name: '${{ matrix.package.name }}'
          user_name: "GitHub Action"
          user_email: "action@github.com"
          branch: "master"